version: "{branch}-ci-{build}"
clone_depth: 5 

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

environment:
  global:
    BOOST_INCLUDEDIR: C:/Libraries/boost_1_59_0
    BOOST_LIBRARYDIR: C:/Libraries/boost_1_59_0/lib64-msvc-14.0
    BUILD_TYPE: Release
    CMAKE_INCLUDE_PATH: C:/projects/dakara-server/deps/libevent_vc120/build/native/include
    CMAKE_LIBRARY_PATH: C:/projects/dakara-server/deps/libevent_vc120/build/native/bin
    LIBEVENT_DLL_PATH: C:/projects/dakara-server/deps/libevent_vc120/build/native/bin
    DAKARA_ARTIFACT: dakara-server-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%-%APPVEYOR_JOB_ID%.zip

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: echo %platform%

before_build:
  - mkdir deps
  - mkdir deps\include
  - mkdir deps\lib
  - nuget install libevent_vc120 -OutputDirectory deps -ExcludeVersion 

build_script:
#  - dir /s /p %BOOST_ROOT%
#  - dir /s /p deps
  - echo %configuration%
  - mkdir build
  - pushd .
  - cd build
  - cmake --version
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release

build:
  parallel: true
  verbosity: detailed

after_build:
#  - cp %LIBEVENT_DLL_PATH%/libevent-x64-v120-mt-2_1_4_0.dll %APPVEYOR_BUILD_FOLDER%/build/Release/
  - cp %LIBEVENT_DLL_PATH%/libevent-x64-v120-mt-2_1_4_0.dll %APPVEYOR_BUILD_FOLDER%/build/Release/libevent.dll
  - cp %BOOST_LIBRARYDIR%/boost_date_time-vc140-mt-1_59.dll %APPVEYOR_BUILD_FOLDER%/build/Release/
  - cp %BOOST_LIBRARYDIR%/boost_filesystem-vc140-mt-1_59.dll %APPVEYOR_BUILD_FOLDER%/build/Release/
  - cp %BOOST_LIBRARYDIR%/boost_system-vc140-mt-1_59.dll %APPVEYOR_BUILD_FOLDER%/build/Release/
  - cp %BOOST_LIBRARYDIR%/boost_locale-vc140-mt-1_59.dll %APPVEYOR_BUILD_FOLDER%/build/Release/
  - cp %BOOST_LIBRARYDIR%/boost_thread-vc140-mt-1_59.dll %APPVEYOR_BUILD_FOLDER%/build/Release/
  - 7z a -mx=9 -xr!.git -xr!dakaraserver.dir -xr!*.ilk -xr!*.pdb -xr!*.nupkg -xr!deps %DAKARA_ARTIFACT% %APPVEYOR_BUILD_FOLDER%
  - appveyor PushArtifact %DAKARA_ARTIFACT%

artifacts:
  - path: '*.zip'
    name: dakaraserver

deploy:
  - provider: FTP
    protocol: ftps
    server:
      secure: C6tkq+q/3l6LiQ4CGNgMhLWvzaajInbUEeruKHhC2lo=
    username:
      secure: rV1YaUrUXNT47IZB1YVFO/D29cj5pGxga5fox8pEy9s=
    password:
      secure: b0B/dtBHOEaFQAqiyT4Ysg==
    folder: /dakara-server
    artifact: 

branches:
  only:
    - master
